### ISSUE TITLE
[BUG] fails to build

### ISSUE THREAD

**Issue by qexat** [trag1c/crossandra#3] opened 2022-12-20 02:32 UTC
Fails to build when installing it from the AUR:
```
* Getting build dependencies for wheel...
validate_pyproject.api.load_builtin_plugin defines `tool.distutils` schema
validate_pyproject.api.load_builtin_plugin defines `tool.setuptools` schema
running egg_info
writing crossandra.egg-info/PKG-INFO
writing dependency_links to crossandra.egg-info/dependency_links.txt
writing requirements to crossandra.egg-info/requires.txt
writing top-level names to crossandra.egg-info/top_level.txt
reading manifest file 'crossandra.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'crossandra.egg-info/SOURCES.txt'

ERROR Missing dependencies:
setuptools
jaraco.text -> inflect -> pydantic>=1.9.1 -> typing-extensions>=4.1.0
==> ERROR: A failure occurred in build().
Aborting...
-> error making: python-crossandra
```

The mentioned dependencies are installed:
```
❯ yay -Qs python-jaraco.text
local/python-jaraco.text 3.11.0-1
Module for text manipulation

❯ yay -Qs python-inflect
local/python-inflect 6.0.2-1
Correctly generate plurals, singular nouns, ordinals, indefinite articles

❯ yay -Qs python-pydantic
local/python-pydantic 1.10.2-1
Data parsing and validation using Python type hints

❯ yay -Qs python-typing-extensions
local/python-typing_extensions 4.4.0-1
Backported and Experimental Type Hints for Python 3.7+
```

Package version: 1.2.4-1
OS version: EndeavourOS, kernel: 6.0.12-arch1-1 (64-bit)

**Comment by MithicSpirit** [comment] 2022-12-20 04:37
Please report AUR issues in the comments on the AUR page. Also, note that `yay` is not officially supported; I would recommend using `makepkg` when you're facing issues like this.

**Comment by MithicSpirit** [comment] 2022-12-22 16:04
I cannot reproduce this issue, even in a clean docker container (archlinux:base-devel), so it is invalid as far as I am concerned. If you figure out how to reproduce it in docker, please report it [on the AUR](https://aur.archlinux.org/packages/python-crossandra). Regardless, this issue should not be on github and can be closed as far as I am concerned.

Alternatively, you can also try building it in a clean chroot. An explanation of how to do this is available [on the wiki](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) (the AUR helper [`paru`](https://github.com/Morganamilo/paru) also has support for this).

**Comment by trag1c** [comment] 2023-02-05 03:40
Closing due to inactivity

**Closed by trag1c** 2023-02-05 03:40 UTC
Labels: bug
